name: bRankup
version: '${project.version}'
main: net.bumpier.brankup.bRankup
api-version: '1.21'
author: bumpier.dev
description: '${project.description}'
softdepend: [Vault, PlaceholderAPI]

permissions:
  brankup.admin:
    description: Grants access to all bRankup admin commands.
    default: op
  brankup.admin.performance:
    description: Allows access to performance monitoring commands.
    default: op
  brankup.admin.progression:
    description: Allows access to progression management commands.
    default: op

commands:
  brankupadmin:
    description: Admin commands for the bRankup plugin.
    aliases: [ bra ]
    permission: brankup.admin
  performance:
    description: Monitor plugin performance and statistics.
    aliases: [ perf ]
    permission: brankup.admin.performance
  progression:
    description: Manage progression types and view system information.
    aliases: [ prog ]
    permission: brankup.admin.progression
